name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: export secrets
        run:
          echo "api.service=${{ secrets.API_SERVICE }}" >> local.properties
          echo "api.key=${{ secrets.API_KEY }}" >> local.properties
      - name: Build App Distribution
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :app:bundleRelease
      - uses: r0adkll/sign-android-release@v1
        id: sign_bundle
        name: Sign AAB
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: Abushawish/upload-google-play@master
        name: Release on Play Store
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: dev.schlaubi.passconverter
          status: completed
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          track: internal